name: CI

on:
  push:
  workflow_dispatch:

env:
  NODE_VERSION: "17.6.0"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Restore npm cache if exists
        uses: actions/cache@v2
        env:
          cache-name: myFortune
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |-
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-

      - name: Setup node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run typecheck

      - name: Run lint
        run: npm run lint

      - name: Run test
        run: npm test